[应用程序]
标题=秀贤
package.name=秀贤
package.domain=org.example
source.dir=。
source.include_exts=py，png，jpg，kv，atlas
版本=0.1
要求=python3，kivy
方向=纵向
全屏=0
android.permissions=INTERNET
android.api=30
android.minapi=21
android.ndk=23b
android.sdk=30
android.arch=armeabi-v7a
osx.python_version=3
osx.kivy_version=1.10.1
